version: '3.1'

services:
  db:
    image: mysql:5.6
    container_name: mysql5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=test
    volumes:
      - ./data:/var/lib/mysql
